# Generated by Django 5.1 on 2024-08-13 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200, verbose_name='Email')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.role')),
            ],
        ),
    ]
